# https://bytemedirk.medium.com/developing-locally-with-dockerized-apache-airflow-and-postgres-a2890b8ae199
# docker exec extract-transform-load-webserver-1 airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com

services:
  postgres:
    image: postgres:15.2
    platform: linux/amd64
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d

  scheduler:
    build:
      context: .
    command: >
      bash -c "
      airflow db migrate &&
      airflow scheduler"
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./scripts/scheduler:/docker-entrypoint-initdb.d
      - /Users/stiborv/Documents/2324/ZS2324/NPRG045/App/backend-v2/extract-transform-load/data:/extract-transform-load/data

  webserver:
    build:
      context: .
    ports:
      - "8080:8080"
    command: >
      bash -c "
      airflow db migrate &&
      airflow webserver -p 8080"
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./scripts/webserver:/docker-entrypoint-initdb.d
      - /Users/stiborv/Documents/2324/ZS2324/NPRG045/App/backend-v2/extract-transform-load/data:/extract-transform-load/data
volumes:
  postgres_data:
